FROM node:lts-alpine

# Install pnpm
RUN npm install -g pnpm

WORKDIR /app

# Copy pnpm-lock.yaml in addition to package.json
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile

COPY . .

# Set default values for build-time environment variables
ARG NUXT_WEBHOOK_CLIENT_ID
ARG NUXT_WEBHOOK_URL
ARG NUXT_WEBHOOK_CLIENT_SECRET
ARG NUXT_JWT_SECRET
ARG AUTH_TOKEN
ARG AWS_KEY
ARG AWS_SECRET
ARG BACKEND_URL
ARG NODE_OPTIONS
ARG NUXT_CRYPTO_STRING_KEY
ARG NUXT_CRYPTO_STRING_SALT
ARG NUXT_DB_URL
ARG NUXT_FILE_ENCRYPTION_KEY
ARG NUXT_GITHUB_TOKEN
ARG NUXT_OAUTH_GITHUB_CLIENT_ID
ARG NUXT_OAUTH_GITHUB_CLIENT_SECRET
ARG NUXT_SESSION_PASSWORD
ARG NUXT_TURSO_TOKEN
ARG NUXT_UI_PRO_LICENSE
ARG PROD

# Set environment variables with build-time args
ENV NUXT_WEBHOOK_CLIENT_ID=$NUXT_WEBHOOK_CLIENT_ID
ENV NUXT_WEBHOOK_URL=$NUXT_WEBHOOK_URL
ENV NUXT_WEBHOOK_CLIENT_SECRET=$NUXT_WEBHOOK_CLIENT_SECRET
ENV NUXT_JWT_SECRET=$NUXT_JWT_SECRET
ENV AUTH_TOKEN=$AUTH_TOKEN
ENV AWS_KEY=$AWS_KEY
ENV AWS_SECRET=$AWS_SECRET
ENV BACKEND_URL=$BACKEND_URL
ENV NODE_OPTIONS=$NODE_OPTIONS
ENV NUXT_CRYPTO_STRING_KEY=$NUXT_CRYPTO_STRING_KEY
ENV NUXT_CRYPTO_STRING_SALT=$NUXT_CRYPTO_STRING_SALT
ENV NUXT_DB_URL=$NUXT_DB_URL
ENV NUXT_FILE_ENCRYPTION_KEY=$NUXT_FILE_ENCRYPTION_KEY
ENV NUXT_GITHUB_TOKEN=$NUXT_GITHUB_TOKEN
ENV NUXT_OAUTH_GITHUB_CLIENT_ID=$NUXT_OAUTH_GITHUB_CLIENT_ID
ENV NUXT_OAUTH_GITHUB_CLIENT_SECRET=$NUXT_OAUTH_GITHUB_CLIENT_SECRET
ENV NUXT_SESSION_PASSWORD=$NUXT_SESSION_PASSWORD
ENV NUXT_TURSO_TOKEN=$NUXT_TURSO_TOKEN
ENV NUXT_UI_PRO_LICENSE=$NUXT_UI_PRO_LICENSE
ENV PROD=$PROD

# Build the Nuxt 3 application
RUN pnpm run build

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
