name: Build and Push to ECR

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::150301572911:role/github-oidc-provider-aws
        role-session-name: push-to-ecr
        aws-region: us-east-1

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: "public.ecr.aws/t7q1f7c9/flakery:latest"
        # cache-from: type=gha
        # cache-to: type=gha,mode=max
        build-args: |
          NUXT_WEBHOOK_CLIENT_ID=${{ secrets.NUXT_WEBHOOK_CLIENT_ID }}
          NUXT_WEBHOOK_URL="https://flakery.dev/api/template/webhook"
          NUXT_WEBHOOK_CLIENT_SECRET=${{ secrets.NUXT_WEBHOOK_CLIENT_SECRET }}
          NUXT_JWT_SECRET=${{ secrets.NUXT_JWT_SECRET }}
          AWS_KEY=${{ secrets.AWS_KEY }}
          AWS_SECRET=${{ secrets.AWS_SECRET }}
          BACKEND_URL=${{ secrets.BACKEND_URL }}
          NODE_OPTIONS="--max_old_space_size=4096"
          NUXT_CRYPTO_STRING_KEY=${{ secrets.NUXT_CRYPTO_STRING_KEY }}
          NUXT_CRYPTO_STRING_SALT=${{ secrets.NUXT_CRYPTO_STRING_SALT }}
          NUXT_DB_URL="libsql://flakery-r33drichards.turso.io"
          NUXT_FILE_ENCRYPTION_KEY=${{ secrets.NUXT_FILE_ENCRYPTION_KEY }}
          NUXT_GITHUB_TOKEN=${{ secrets.NUXT_GITHUB_TOKEN }}
          NUXT_OAUTH_GITHUB_CLIENT_ID=${{ secrets.NUXT_OAUTH_GITHUB_CLIENT_ID }}
          NUXT_OAUTH_GITHUB_CLIENT_SECRET=${{ secrets.NUXT_OAUTH_GITHUB_CLIENT_SECRET }}
          NUXT_SESSION_PASSWORD=${{ secrets.NUXT_SESSION_PASSWORD }}
          NUXT_TURSO_TOKEN=${{ secrets.NUXT_TURSO_TOKEN }}
          NUXT_UI_PRO_LICENSE=${{ secrets.NUXT_UI_PRO_LICENSE }}
          PROD=1


